- name: restart pinger
  service:
    name: pinger
    state: restarted

- name: restart InfluxDB
  service:
    name: influxdb
    state: restarted

- name: restart Telegraf
  service:
    name: telegraf
    state: restarted

- name: restart MySQL exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted


- name: restart node exporter
  service:
    name: prometheus-node-exporter
    state: restarted

- name: Stop grafana Container
  docker_container:
    name: grafana
    state: stopped

- name: Delete default grafana.db
  file:
    path: /opt/docker/grafana/grafana.db
    state: absent

- name: Copy new db file to dest
  copy:
    src: /home/ubuntu/grafana.db
    dest: /opt/docker/grafana/grafana.db
    remote_src: yes

- name: Grafana.db rights
  file:
    path: /opt/docker/grafana/grafana.db
    owner: "472"
    group: "472"

- name: Start grafana Container
  docker_container:
    name: grafana
    state: started