- name: update repo cache and update "nginx" to latest
  apt:
    name: nginx
    state: latest
    update-cache: yes

- name: copy config file to dst
  template:
    src: node_exporter.j2
    dest: /etc/nginx/sites-enabled
  notify:
  - restart nginx
  