- name: update repo cache and update "nginx" to latest
  apt:
    name: nginx
    state: latest
    update-cache: yes

- name: No default nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Restart nginx

- name: copy config file to dst
  template:
    src: node_exporter.j2
    dest: /etc/nginx/sites-enabled/node_exporter
  notify:
  - restart nginx