- name: Install haproxy package
  apt:
    pkg:
      - haproxy

- name: Start haproxy service
  service:
    name: haproxy
    state: started

- name: HAProxy config
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
#    - stop nginx
    - restart haproxy

- name: Install docker.io
  apt:
    pkg:
      - docker.io
      - python3-docker
    update_cache: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: HAProxy exporter
  docker_container:
    name: haproxy_exporter
    image: quay.io/prometheus/haproxy-exporter:v0.9.0
    ports:
      - 9101:9101
    command: --haproxy.scrape-uri="http://172.17.0.1:88/haproxy?stats;csv" 