- name: Install dependencies
  apt:
    pkg:
    - apt-transport-https
    - software-properties-common

- name: Add gpg key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add specified repository into sources list
  apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present

- name: Install Grafana
  apt:
    pkg:
    - grafana-enterprise
    state: latest
    update_cache: yes

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  
- name: Enable Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes