- name: Install dependencies
  apt:
    pkg:
    - apt-transport-https
    - software-properties-common
    - adduser
    - libfontconfig1

- name: Download grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.2.2_amd64.deb
    dest: /tmp/grafana_7.2.2_amd64.deb

- name: install Grafana
  apt:
    deb: /tmp/grafana_7.2.2_amd64.deb

- name: Copy grafana.ini
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - restart grafana-server
  
- name: Enable Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes