- name: Install uwsgi
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3
    state: latest
    update_cache: yes

- name: Install mysql python package
  apt:
    name: python3-pymysql
    state: present
 
- name: Move agama.ini to dest
  template:
    src: ./agama.ini
    dest: /etc/uwsgi/apps-enabled
  notify:
  - restart uwsgi
