- name: Create folder for grafana
  file:
    path: /opt/docker/grafana
    state: directory
    owner: "472"
    group: "472"
    
- name: Create grafana Container
  docker_container:
    name: grafana
    image: grafana/grafana
    volumes:
      - /opt/docker/grafana:/var/lib/grafana
    ports:
      - "{{ grafana_port }}:3000"
    env:
      GF_SERVER_ROOT_URL: "http://localhost:{{ grafana_port }}/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

- name: Start grafana Container
  docker_container:
    name: grafana
    state: started

- name: Download grafana.db
  get_url:
    url: https://github.com/saartanel/infra/raw/main/grafana.db
    dest: /home/ubuntu/
  notify:
    - Stop grafana Container
    - Delete default grafana.db
    - Copy new db file to dest
    - Grafana.db rights
    - Start grafana Container