- name: Create folder for grafana
  file:
    path: /opt/docker/grafana
    state: directory
    owner: "472"
    group: "472"
    
- name: Create grafana Container
  docker_container:
    name: grafana
    image: grafana/grafana
    volumes:
      - /opt/docker/grafana:/var/lib/grafana
    ports:
      - "{{ grafana_port }}:3000"
    env:
      GF_SERVER_ROOT_URL: "http://localhost:{{ grafana_port }}/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"