- name: Setup
  hosts: all
  tasks:
    - setup:

- name: Bind9 server
  become: yes
  hosts: dns_servers
  gather_facts: no
  roles:
    - bind
  tags:
    - bind

- name: Bind9 exporter
  become: yes
  hosts: dns_servers
  gather_facts: no
  roles:
    - bind_exporter
  tags:
    - bind_exporter

- name: Database server
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
    - mysql_exporter
  tags:
    - mysql

- name: Web app
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - nginx
    - nginx_exporter
    - node_exporter
  tags:
    - web_app

- name: Haproxy
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - haproxy
  tags:
    - haproxy

- name: Keepalived
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - keepalived
  tags:
    - keepalived
    
- name: Prometheus
  hosts: prometheus
  become: yes
  gather_facts: no
  roles:
    - prometheus
  tags:
    - prometheus

- name: Backup user
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - backup
  tags:
    - backup

- name: General monitoring
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - rsyslog
  tags:
    - monitoring

- name: Influxdb
  hosts: influxdb
  become: yes
  gather_facts: no
  roles:
    - influxdb
    - pinger
  tags:
    - influxdb

- name: Docker
  hosts: docker
  become: yes
  gather_facts: no
  roles:
    - docker
    - node_exporter
  tags:
    - docker
  
- name: Grafana Docker
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana_docker
  tags:
    - grafana_docker

- name: Agama Docker
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - agama_docker
  tags:
    - agama_docker
