- name: Collect info about all VMs
  hosts: all
  tasks:
    - setup:
    - debug:
  
- name: Bind9 server
  become: yes
  vars_files:
    - group_vars/dns_var.yaml
  hosts:
    saartanel-2
  roles:
    - bind9