- name: Collect info about all VMs
  hosts: all
  tasks:
    - setup:
  
- name: Bind9 server
  become: yes
  hosts:
    saartanel-2
  roles:
    - bind
  
- name: change resolv.conf
  become: yes
  hosts: all
  tasks:
    - template:
        src: ./roles/bind9/templates/resolv.conf.j2
        dest: /etc/resolv.conf