- name: Setup
  hosts: all
  tasks:
    - setup:

- name: Bind9 server
  become: yes
  hosts: dns_servers
  gather_facts: no
  roles:
    - bind
    - bind_exporter
  tags:
    - bind

- name: Database server
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
    - mysql_exporter
  tags:
    - mysql

- name: Web app
  hosts: app_servers
  become: yes
  gather_facts: no
  roles:
    - agama
    - uwsgi
    - nginx
    - nginx_exporter
    - node_exporter
  tags:
    - web_app

- name: Grafana
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana
  tags:
    - grafana

- name: Prometheus
  hosts: prometheus
  become: yes
  gather_facts: no
  roles:
    - prometheus
  tags:
    - prometheus

- name: Backup user
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - backup
  tags:
    - backup

- name: General monitoring
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - rsyslog
  tags:
    - monitoring

- name: Influxdb
  hosts: influxdb
  become: yes
  gather_facts: no
  roles:
    - influxdb
    - pinger
  tags:
    - influxdb