- name: Setup
  hosts: all
  tasks:
    - setup:

- name: Haproxy
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - haproxy
  tags:
    - haproxy

- name: Keepalived
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - keepalived
  tags:
    - keepalived

- name: Prometheus
  hosts: prometheus
  become: yes
  gather_facts: no
  roles:
    - prometheus
  tags:
    - prometheus