- name: Setup
  hosts: all
  tasks:
    - setup:

- name: Backup user
  hosts: all
  become: yes
  roles:
    - backup
  tags:
    - backup

- name: Prometheus
  hosts: prometheus
  become: yes
  gather_facts: yes
  roles:
    - prometheus
  tags:
    - prometheus

- name: Bind_exporter
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind_exporter
  tags:
    - bind_exporter
  
- name: Mysql_exporter
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql_exporter
  tags:
    - mysql_exporter

- name: Nginx_exporter
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - nginx_exporter
  tags:
    - nginx_exporter

- name: Grafana
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana
  tags:
    - grafana

- name: General monitoring
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - node_exporter
    - rsyslog
  tags:
    - rsyslog

- name: Influxdb
  hosts: influxdb
  become: yes
  gather_facts: no
  roles:
    - influxdb
  tags:
    - influxdb

- name: Pinger
  hosts: influxdb
  become: yes
  gather_facts: no
  roles:
    - pinger
  tags:
    - pinger