- name: Install mysql
  apt:
    pkg:
    - mysql-server
    - python3-pymysql
    state: latest
    update_cache: yes

- name: Override mysqld config
  template:
    src: ./override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
  - restart mysql

- name: MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Replication user
  mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Copy slave script to master
  template:
    src: slave.sql
    dest: /etc/mysql/slave.sql
  when:
    - inventory_hostname in groups['db_servers'][0]
  notify:
    - slave script