---
- name: Exporter packages
  apt:
    pkg: 
      - prometheus-node-exporter
      - nginx
    update_cache: yes

- name: No default nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Restart nginx

- name: Nginx config
  template:
    src: node_exporter.j2
    dest: /etc/nginx/sites-enabled/node_exporter
  notify:
    - Restart nginx

- name: change resolv.conf
  template:
    src: ./resolv.conf.j2
    dest: /etc/resolv.conf