---
- name: Install prometheus
  apt:
    pkg: 
      - prometheus
    state: latest
    update_cache: yes

- name: Ensure prometheus is running
  service:
    name: prometheus
    state: started

- name: Copy ARGS file
  template:
    src: prometheus
    dest: /etc/default/prometheus
  notify:
    - Restart prometheus
    
- name: Copy jobs file
  template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart prometheus