- name: Install Bind9
  apt:
    pkg:
    - bind9
    - python3-dnspython
    state: latest
    update_cache: yes

- name: Ensure Bind9 is running
  service:
    name: bind9
    state: started
    enabled: yes

- name: Copy named.conf.options to /etc/bind
  template:
    src: ./named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
  - restart bind9

- name: Copy named.conf.local to /etc/bind
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    - restart bind9
  when: inventory_hostname in groups['dns_masters']

- name: Copy named.conf.local.slave to /etc/bind
  template:
    src: named.conf.local.slave.j2
    dest: /etc/bind/named.conf.local
  notify:
    - restart bind9
  when: inventory_hostname in groups['dns_slaves']

- name: Copy db.toenail to /etc/bind
  template:
    src: ./db.toenail
    dest: /var/lib/bind/
  notify:
  - restart bind9
  - rndc reload
  when: inventory_hostname in groups['dns_masters']

- name: change resolv.conf
  template:
    src: ./resolv.conf.j2
    dest: /etc/resolv.conf
