- name: Create system user named agama
  user:
    name: agama
    state: present
    system: yes

- name: Create directory named agama
  file:
    path: /opt/agama
    state: directory
    owner: agama

- name: Download Agama DockerFile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Build Agama Docker image
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      pull: no

- name: Create Agama Container
  docker_container:
    name: agama
    image: agama
    ports:
      - "{{ agama_port }}:8000"
    env:
      AGAMA_DATABASE_URI: mysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}

- name: Start Agama Container
  docker_container:
    name: agama
    state: started