- name: Create Agama folder for Docker
  file:
    path: /opt/agama
    state: directory

- name: Download Agama DockerFile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile

- name: Build Agama Docker image
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      pull: no

- name: Create Agama Container
  docker_container:
    name: agama
    image: agama
    ports:
      - "{{ agama_port }}:8000"
    env:
      AGAMA_DATABASE_URI: mysql://{{ mysql_user}}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}